### ISSUE TITLE
Problem with "Microsoft/vcpkg" while building for Linux Mint 19.3

### ISSUE THREAD

**Issue by mikebdp2** [vircadia/vircadia-builder#5] opened 2020-02-06 06:59 UTC
@daleglass Just tried to build on Linux Mint 19.3 and encountered this error. I don't understand, why such an awesome stuff like project-athena has to rely on M$ crappy products...
[athena-builder-error-2020-01-06_T09_52_11.tar.gz](https://github.com/daleglass/athena-builder/files/4163617/athena-builder-error-2020-01-06_T09_52_11.tar.gz)
[install-x64-linux-dbg-out.log](https://github.com/daleglass/athena-builder/files/4163631/install-x64-linux-dbg-out.log)
```
./athena_builder --build server,client --collect-info
Checking how many cores to use for building Athena... 8 cores, memory limited to 5
Checking how many cores to use for building Qt... 8 cores, memory limited to 4
Detecting desktop location... /home/owner/Desktop
Detecting distribution... Linux Mint 19.3 (linuxmint-19.3)
Getting the package list... done.
Checking Qt availability...There is no binary Qt package available for your system!

This script can build it for you, but it can take a long time,
up to several hours, depending on hardware capabilities.

Fortunately, it only needs to be built once.

Checking if any packages need installing... no.

Everything seems to be in order. I am going to ask you some questions now.
The defaults should be just fine. Simply press ENTER to accept the suggested
value.

Git repository             : https://github.com/kasenvr/project-athena
Git tag                    : kasen/core
Installation dir           : /home/owner/Athena
CPU cores to use for Athena: 5
CPU cores to use for Qt5   : 4

If the above is okay, say 'yes' to begin installation: yes


############################################################
# Starting installation
############################################################

Getting source from git https://github.com/kasenvr/project-athena (kasen/core)...
Checking if updating the existing source is possible... yes
Already cloned, updating...
HEAD сейчас на 7833a49784 Merge pull request #148 from ctrlaltdavid/fix/jsdoc-dev-env
Checking whether Qt is already installed... yes.
Skipping Qt5 build. You can remove /home/owner/Athena/qt5-install if you want to force it to be rebuilt.


############################################################
# Building
############################################################

Checking whether Qt is already installed... yes.
Using compiled Qt
-- EXTERNAL_BUILD_ASSETS: https://athena-public.s3.amazonaws.com
-- Found PythonInterp: /usr/bin/python3 (found version "3.6.9") 
['/home/owner/Athena/source/prebuild.py', '--release-type', 'DEV', '--build-root', '/home/owner/Athena/build']
Using vcpkg path /home/owner/Athena/vcpkg/20693e10
Writing tag 20693e10_1 to /home/owner/Athena/vcpkg/20693e10/.id
Installing host tools
Running command
['/home/owner/Athena/vcpkg/20693e10/vcpkg', '--vcpkg-root', '/home/owner/Athena/vcpkg/20693e10', 'install', '--triplet', 'x64-linux', 'hifi-host-tools']
The following packages are already installed:
    hifi-host-tools[core]:x64-linux
Starting package 1/1: hifi-host-tools:x64-linux
Package hifi-host-tools:x64-linux is already installed
Elapsed time for package hifi-host-tools:x64-linux: 7.105 us

Total elapsed time: 13.45 us

Installing build dependencies
Running command
['/home/owner/Athena/vcpkg/20693e10/vcpkg', '--vcpkg-root', '/home/owner/Athena/vcpkg/20693e10', 'install', '--triplet', 'x64-linux', 'hifi-client-deps']
The following packages will be built and installed:
  * bullet3[core]:x64-linux
  * draco[core]:x64-linux
  * etc2comp[core]:x64-linux
    hifi-client-deps[core]:x64-linux
  * hifi-deps[core]:x64-linux
  * nlohmann-json[core]:x64-linux
  * nvtt[core]:x64-linux
  * openexr[core]:x64-linux
  * opus[core]:x64-linux
  * sdl2[core]:x64-linux
  * tbb[core]:x64-linux
  * webrtc[core]:x64-linux
  * zlib[core]:x64-linux
Additional packages (*) will be modified to complete this operation.
Starting package 1/13: etc2comp:x64-linux
Building package etc2comp[core]:x64-linux... 
-- Using cached /home/owner/Athena/vcpkg/20693e10/downloads/kasenvr-etc2comp-7f1843bf07825c21cab711360c1ddbad04641036.tar.gz
-- Using source at /home/owner/Athena/vcpkg/20693e10/buildtrees/etc2comp/src/ad04641036-f22e3c7392
-- Configuring x64-linux-dbg
-- Configuring x64-linux-rel
-- Building x64-linux-dbg
CMake Error at scripts/cmake/vcpkg_build_cmake.cmake:175 (message):
    Command failed: /home/owner/Athena/vcpkg/20693e10/downloads/tools/cmake-3.11.4-linux/cmake-3.11.4-Linux-x86_64/bin/cmake;--build;.;--config;Debug;--target;install;--;-v;-j1
    Working Directory: /home/owner/Athena/vcpkg/20693e10/buildtrees/etc2comp/x64-linux-dbg
    See logs for more information:
      /home/owner/Athena/vcpkg/20693e10/buildtrees/etc2comp/install-x64-linux-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/etc2comp/portfile.cmake:32 (vcpkg_install_cmake)
  scripts/ports.cmake:71 (include)


Error: Building package etc2comp:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: etc2comp:x64-linux
  Vcpkg version: 2018.10.20-unknownhash

Additionally, attach any relevant sections from the log files above.
Traceback (most recent call last):
  File "/home/owner/Athena/source/prebuild.py", line 163, in <module>
    main()
  File "/home/owner/Athena/source/prebuild.py", line 138, in main
    pm.setupDependencies()
  File "/home/owner/Athena/source/hifi_vcpkg.py", line 204, in setupDependencies
    self.run(['install', '--triplet', self.triplet, 'hifi-client-deps'])
  File "/home/owner/Athena/source/hifi_vcpkg.py", line 189, in run
    hifi_utils.executeSubprocess(actualCommands, folder=self.path)
  File "/home/owner/Athena/source/hifi_utils.py", line 64, in executeSubprocess
    ' '.join(processArgs[1:]),
RuntimeError: Call to "/home/owner/Athena/vcpkg/20693e10/vcpkg" failed.

arguments:
--vcpkg-root /home/owner/Athena/vcpkg/20693e10 install --triplet x64-linux hifi-client-deps

CMake Error at CMakeLists.txt:81 (message):
  vcpkg configuration missing.


-- Configuring incomplete, errors occurred!
Collecting additional system info to aid with debugging...

Fatal error:
Command 'cmake ../source' exited with value 1


Logs have been collected in athena-builder-error-2020-01-06_T09_52_11.tar.gz
Please notify Dale Glass#8576 on Discord of this problem.
```

**Comment by daleglass** [comment] 2020-02-06 08:00
Hello, could you include the contents of this file?

      /home/owner/Athena/vcpkg/20693e10/buildtrees/etc2comp/install-x64-linux-dbg-out.log

Thanks!

**Comment by mikebdp2** [comment] 2020-02-07 14:10
Hi @daleglass , I've included it to a top of this message - here's a repost:
[athena-builder-error-2020-01-06_T09_52_11.tar.gz](https://github.com/daleglass/athena-builder/files/4163617/athena-builder-error-2020-01-06_T09_52_11.tar.gz)
[install-x64-linux-dbg-out.log](https://github.com/daleglass/athena-builder/files/4163631/install-x64-linux-dbg-out.log)

**Comment by daleglass** [comment] 2020-02-07 20:31
Whoops, sorry about that. I'm a bit distracted here, currently on vacation and looking at stuff during idle times.

Anyway, hmm... that's interesting. It looks like there are multiple math.h files on the system, and the build is picking up the wrong one. This looks wrong for example:

    In file included from /usr/include/c++/7/math.h:36:0,
    ...
    /usr/include/c++/4.8/cmath:102:11: error: ‘::acos’ has not been declared

Unfortunately my Mint install is in a VM on my home machine, which is a bit hard to get to right now. I will be back home on Sunday.

Meanwhile, if you'd like to experiment, perhaps try to remove `g++-4.8` and `libstdc++-4.8-dev`. Having less compilers around might help.

This may be a bug in either the etc2comp package, or the vcpkg bit that corresponds to it.

**Comment by daleglass** [comment] 2020-02-07 20:32
This seems to be another example of the same issue: https://stackoverflow.com/questions/1436326/cmath-errors-when-using-fltk

**Comment by daleglass** [comment] 2020-02-11 19:16
Still looking into this. Removing g++4.8 should work as a temporary fix, but this seems to be an issue in the main code tree.

**Comment by jug007** [comment] 2020-03-29 10:12
Just for the record: I successfully build this on Linux Mint 19.3 yesterday and didn't run into this partucular issue. My Linux Mint installation is quite old and has been used a lot though, so it might not be 100% comparable to a less hacked one.

**Comment by JulianGro** [comment] 2021-07-16 07:25
I am closing this as no one has been able to reproduce this issue.
If this is still an issue, just reopen.

**Closed by JulianGro** 2021-07-16 07:25 UTC
